# Generated by Django 4.2.7 on 2023-11-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('quantity_sell', models.IntegerField(verbose_name='Кол-во сделок')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№ квартиры')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('square', models.CharField(max_length=100, verbose_name='КВ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('client', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Клиент')),
                ('flat_status', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.category', verbose_name='Объект')),
            ],
        ),
    ]
