# Generated by Django 4.2.7 on 2023-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='client_number',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Номер клиента'),
        ),
        migrations.AddField(
            model_name='flat',
            name='contract_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='№ Договора'),
        ),
    ]
