# Generated by Django 4.2.7 on 2023-11-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_flat_client_number_flat_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Временный пароль'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='quantity_sell',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во сделок'),
        ),
    ]
